### ISSUE TITLE
CSV export cannot be used as a backup

### ISSUE THREAD

**Issue by kmantel** [Razeeman/Android-SimpleTimeTracker#129]
Why can't CSV be used as a backup? Is there missing data?

https://github.com/Razeeman/Android-SimpleTimeTracker/blob/ca8ef950e8608c945e59ef8d65ce00422291b83f/features/feature_settings/src/main/res/layout/settings_export_import_layout.xml#L81-L86

**Comment by gito458** [comment]
If you reinstall the app and then perform a CSV import as a restore, only time entries are entered. Only the activities and comments are imported, tags and categories are not. 

You would also have to manually recreate the activity, tag and category list. I believe this limitation is because the links between activities, categories and tags cannot be mapped via a CSV file.

**Comment by Razeeman** [comment]
Csv file contains only a portion of data that is needed to work in a spreadsheet program. Although other data can be put into csv (colors, relaions, tag etc), it was not meant for it. Hope it makes sense.
