### ISSUE TITLE
[Bug] Saving activity to have same name as another silently updates the other activity

### ISSUE THREAD

**Issue by kmantel** [Razeeman/Android-SimpleTimeTracker#131]
1. Create two activities 1 named A and 2 named B
2. Edit name of activity 1 to B
3. Everything but categories is modified on activity 2 to the values of activity 1 and activity 1 remains unchanged

I noticed this because I intended to have two activities with the same name, but used in different categories. One of the activities had extra whitespace in the name, which I tried to remove, finding this bug.

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. In the old versions there was a limitation coded that no two activities should have same name. Because of that changes would apply to original activity with that name and activity that is being edited woudn not be changed. This logic was changed in the latest releases, now it is possible to have activities with the same name. So this bug should be fixed.
