### ISSUE TITLE
Pause tracking

### ISSUE THREAD

**Issue by nuid64** [Razeeman/Android-SimpleTimeTracker#135]
It would be very convenient if there were an option to suspend current task time tracking if I want to go make a cup of tea or take a shit really fast but not fast enough for the time being counted as "working on X"

**Comment by cogk** [comment]
Does splitting the record in two fit your use case? The way I see your issue, it looks like it would be fixed by the following:

* I start my task, so I tap on the activity to **start the timer**;
* I need to pause 1 hour later, so I **stop the timer**, thus saving a finished record;
* I resume my task 5 minutes later, I tap on the **"Repeat" button to start a new timer** with the same parameters;
* I finish my workday, **stop the timer**, and end up with **_two records separated by 5 minutes of untracked time_**.

**Comment by nuid64** [comment]
Didn't thought about this earlier. There's no need in this function, this will bring unnecessary complexity. Just making two records (and there is 'Repeat' button for convenience, indeed) is more than enough. Thank you for your response.
