### ISSUE TITLE
v1.44 disappeared?

### ISSUE THREAD

**Issue by the-antz** [Razeeman/Android-SimpleTimeTracker#210]
Hi, I use Obtainium to update my apps and somehow it updated me to SimpleTimeTracker v1.44. SimpleTimeTracker shows it's on version 1.44 and the android settings confirm it.
Yet as of writing this, the latest release here is v1.43, there's also no commit for a release of v1.44.
What goes? Was there maybe a v1.44 which was pulled due to issues or something? But why is there no trace of it in the commits?

**Comment by Razeeman** [comment]
Hello! Recently google play started to reject some updates. To avoid spamming with fix releases I make a local release commit, build apk, release in on the app store, and only after it is accepted - release on github. Also I can add github releases only on weekends due to a luck of free time. Because of that, 1.44 is released on the store but not yet on the github. Hope this makes sence.

**Comment by the-antz** [comment]
I probably accidentally updated it from the play store then. I sometimes have this with other apps too and was always wondering. Thanks for the info.
