### ISSUE TITLE
Standard button disappeared 

### ISSUE THREAD

**Issue by CNChem** [Razeeman/Android-SimpleTimeTracker#217]
Hi, the app has been a great way to track my time and I love the simple design, however I have not been able to find one thing. I had a "standard" button on the screen, allowing me to add pre-configured activities and mistakenly deleted it. I can not find any setting to add it again, is this intentional? Or am I overlooking some obvious setting?

**Comment by cogk** [comment]
This screen (see image attached below)? I feel like it's not possible to get it back, unless you backup then reset the app then reimport your backup.

![](https://github.com/user-attachments/assets/abd7e990-cc3c-468f-9522-664fc287ced4)

**Comment by CNChem** [comment]
That's exactly what I ment. Thank you, it's a pity though there isn't an option to en/diable it in the settings.

**Comment by Razeeman** [comment]
Hello! I'm a little bit cautious with adding new settings to avoid feature overload. It is intentional that when "Don't show again" is clicked than the dialog is hidden.

Probably need to add another alert before hiding, like "Are you sure? This action cannot be undone", to avoid accidental click. 

All default activities can be created the usual way, through the add screen. It is just an icon, name and color. 

Also if you absolutely need to return it back, it can be done by slowly clicking five times on the app version in the settings tab. Debug menu will unlock and there will be "Clear default types preference" button. 

Hope this make sense.

**Comment by CNChem** [comment]
Hello, that was a very helpful answer and I understand wanting to avoid feature overload. 
Thank you for making this awesome, simple and straightforward app!
