### ISSUE TITLE
The time entered is unreasonable

### ISSUE THREAD

**Issue by jiaoqingqinggitee** [Razeeman/Android-SimpleTimeTracker#23]
This time data is unreasonable. If there is a prompt, it would be good
![719](https://user-images.githubusercontent.com/84500440/139580941-8757ffec-0aa1-4679-8863-2cfc6aa39c5e.png)

**Comment by neekubee** [comment]
Is this on the goal tab? Does anyone actually specify the seconds?

[Request] Remove the seconds

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. It is the same UI that is used in android system for timer selection. It seems that is more flexible because it allows setting for example 1 minute and 30 second as 01:30 but also as just 00:90. In the end time entered as 00:90 still is converted to 1 minute and 30 seconds.

<img width="386" alt="image" src="https://github.com/Razeeman/Android-SimpleTimeTracker/assets/5223302/d612e3ee-10ca-4d14-8ae4-49a1d278e376">
