### ISSUE TITLE
Activities sorting page pops up unexpected while accessibility service is enabled

### ISSUE THREAD

**Issue by Zocker1999NET** [Razeeman/Android-SimpleTimeTracker#29]
My setup is as follows:
- use Simple Time Tracker and sort activities manually
- close app from task manager
- go into settings and enable any accessibility app service available (tested with "KDE Connect" and "Tap, Tap")
- open Simple Time Tracker and begin editing already logged entry
- exit edit screen by using either the back button or save button
- see sorting page pop up

You can even disable/enable the accessibility service without restarting Simple Time Tracker and see, that the pop up will only show up by itself if any accessibility service is enabled.

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback. A lot of users also mentioned this bug but I'm having a hard time reproducing it on my phones. So I'm kind of trying to fix it blindly. Can you check the app version that is linked here and see if the bug is still present? It's a debug version of the app so it will install separately with the release version and wouldn't affect your data, but just in case make a backup file if you decide to try it.

[app-debug.apk.zip](https://github.com/Razeeman/Android-SimpleTimeTracker/files/8041309/app-debug.apk.zip)

**Comment by kaiwinter** [comment]
I can reproduce this issue when I long press an activity to open the edit view. Then, when I go back, the sorting view pops up. 
![demo.gif](https://user-images.githubusercontent.com/110982/154556925-15e21bb2-4634-4121-84c4-bb4e74658996.gif)


The sorting view also pops up when I open the app from the home screen. This always happens when the app wasn't started before or was forced to end. If the app is running on background when I open it the sorting view doesn't come up.

**Comment by Razeeman** [comment]
@kaiwinter Hello! Thank you for the information. Can you check on the app version that I linked in the previous comment?

**Comment by kaiwinter** [comment]
That one works as expected. I cannot reproduce the problem with that one.

**Comment by kaiwinter** [comment]
Version 1.17 still shows this behaviour 🙁

**Comment by Razeeman** [comment]
> Version 1.17 still shows this behaviour 🙁

Thank you for the information! Seems like this bug needs more digging.

**Comment by kaiwinter** [comment]
Since a couple of days the "sorting page" doesn't popup unexpectedly anymore. I don't know what's different now. I'm using 1.17 all the time.

**Comment by Razeeman** [comment]
@kaiwinter That's weird. By the way 1.18 was released a couple of days ago with a possible fix. Can you update and check if the bug is still present?

**Comment by kaiwinter** [comment]
Just updated to 1.18. I cannot reproduce the bug anymore. Seems to be fixed 🎉 
Thank you for your app and your ongoing work.

**Comment by Razeeman** [comment]
Thanks for the info! I hope it's finally fixed.

**Comment by Zocker1999NET** [comment]
Sorry to say that, but sadly I still can reproduce this bug on 1.18 with "Sort activities" set to "manual". Tested with both accessibility services of KDE Connect and Time Limit (one enabled at a time).
