### ISSUE TITLE
[Feature] Add "show records" toggle directly in calendar view

### ISSUE THREAD

**Issue by preethamrn** [Razeeman/Android-SimpleTimeTracker#46]
Currently, in order to toggle between showing and not showing record in the calendar view, one must go to settings and toggle "Show records in calendar view". It would be more convenient to include the toggle directly in the calendar view.

**Comment by neekubee** [comment]
In a similar note. [feature] That the calendar view does not depend/limit on the phone screen. That it be adjustable via a scroll just like the default record view.

**Comment by Razeeman** [comment]
@preethamrn Hello! Thank you for the suggestion. I think it would be better to keep most of the settings in the settings tab so that the main screens will stay as simple as possible.

@neekubee calendar view allows zooming and scrolling. Do you mean that it would be better if it would be zoomed in by default?

**Comment by neekubee** [comment]
@Razeeman Oh! Sorry, I didn't try to zoom in. I assumed it was fixed. It's okay as it is, thank you!

**Comment by pat-richter** [comment]
Suggestion @Razeeman
If you want to implement the FR, you could split this in multiple tabs instead of showing a different view in the same tab. If so, please add a setting which tabs should be visible - I don't want to have both ;-)

If not, you may add a comment and close this issue.
Kind regards

**Comment by Razeeman** [comment]
Multiple tabs seems like a overcomplication, so probably it will stay as it is for now.
