### ISSUE TITLE
[Suggestion] Wear OS app

### ISSUE THREAD

**Issue by yegarti** [Razeeman/Android-SimpleTimeTracker#60]
More of a question than suggestion, but are there any plans to support on Wear OS for Galaxy and Pixel watches?

Thanks.

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion, I was planning to look into it after the next update, but can't tell for sure if it can be implemented or when.

**Comment by thehale** [comment]
I'd also appreciate a WearOS app so that I can track my time without needing to pull out my phone every time I switch activities. Here's how I would prioritize SimpleTimeTracker's current features for a WearOS version.

Valued Features:
 - See the active activity record alongside its duration and tags.
 - Change the active activity and tags.
 - (Bonus) Edit recent activity records (start time, end time, activity type, tags).

Unnecessary Features:
 - Statistics/Analytics/Charts of any sort
 - Import/Export of data.
 - Changing app settings
 - Adding/editing/removing activities
 - Adding/editing/removing tags

Here's an existing time tracking app with some screenshots showing how it supports smartwatches: https://play.google.com/store/apps/details?id=com.rauscha.apps.timesheet

**Comment by Razeeman** [comment]
@thehale Thank you for the suggestion! If wear os version would be possible to implement, in the first version probably would be the thing you suggested - ability to view current records and change active activities.

**Comment by thehale** [comment]
I started building a sample WearOS app which leverages the automated tracking features from #11 for its functionality.

Check it out here: https://github.com/thehale/SimpleTimeTracker-WearOS

## Features
 - See all your activities
 - See tags associated with activities
 - Show an icon alongside each activity
 - Show each activity in a specific color
 - Chose an activity/tag pair to start tracking
 - Scrolling via a rotating bezel OR side wheel

## Limitations
 - All activities/tags must be hard-coded since there isn't yet a way to programmatically request them from SimpleTimeTracker. As a result, all users of this particular implementation will have to compile their own version.
 - This WearOS app currently works great between two emulators (WearOS Large Round API 28 + Pixel 3 API 30), but refuses to pass messages from my Galaxy Watch 4 Classic (WearOS 3.5) to my Google Pixel (Android 10). Still trying to figure out why.
    - My initial research points to a certificate/signing inconsistency ([source](https://stackoverflow.com/questions/24595170/sending-messages-from-android-wear-to-host-device) and [source](https://developer.android.com/training/wearables/data/messages#:~:text=in%20order%20to%20use%20this%20method%2C%20your%20wear%20os%20app%20and%20phone%20app%20should%20have%20the%20same%20application%20id.)).
    - However, I've ensured my `applicationId` is the same for both the mobile/wear apps, and I ran a debug build where I manually selected the same keystore to sign each application which still didn't work on the physical devices.

**Comment by MicaelJarniac** [comment]
A Wear OS app would be amazing!
And if possible, after the basic implementation, having a tile for quickly switching activities would be awesome.
I love tiles because they're super quick to get to, no need to open the app drawer and look for the app. The tiles are always there, and always easy to get to.

**Comment by christophstoeckl** [comment]
Are there any news on this?

I would also be very interested in a Wear OS app and could also help with the development.

**Comment by thehale** [comment]
@christophstoeckl Yep! Here's the current roadmap for the WearOS app I started a few months ago.

https://github.com/users/thehale/projects/2/views/1

If you join, there would be three of us working on it. The best ticket to work on right now without stepping on other's toes is probably https://github.com/thehale/SimpleTimeTracker-WearOS/issues/7.

**Comment by christophstoeckl** [comment]
@thehale Sounds great, I hope that I can find a bit of time on the weekends to contribute to this!

**Comment by kantahrek** [comment]
Hi @Razeeman! I've teamed up with @thehale to put some work into our "companion WearOS app" for SimpleTimeTracker. We wanted to check in with you on our first round of planned changes to STT to facilitate a Wear<->Mobile integration.

I've made some modifications to [NotificationReceiver](https://github.com/Razeeman/Android-SimpleTimeTracker/blob/dev/features/feature_notification/src/main/java/com/example/util/simpletimetracker/feature_notification/recevier/NotificationReceiver.kt) in my fork of STT (see my changes [here](https://github.com/kantahrek/Android-SimpleTimeTracker/blob/dev/features/feature_notification/src/main/java/com/example/util/simpletimetracker/feature_notification/recevier/NotificationReceiver.kt#L202-L224)) to facilitate passing tracking state data to the Wear. Namely, I've added a pair of Intent handlers to the list that handle the new events "AdhocExportCategories" and "AdhocExportPrefs", which turn around and broadcast back to the calling app, respectively, the current registered categories+whether they're running and whether the user has enabled the "multi-tasking" preference. I believe this is all the information we will need from STT for our app's first iteration.

I could send a PR your way soon; do the changes I've described above make sense to you? Thanks!

**Comment by Razeeman** [comment]
Hello! Looked through suggested changes and they totally make sense. I'd like to make some small changes that I can either write as comments to the pr or can make them myself after pr would be merged, whichever would you prefer.

**Comment by thehale** [comment]
@Razeeman another status update...

We've pivoted to implementing WearOS support directly into a fork of your app. Still not production ready, but the [communication layer between Watch and Phone](https://github.com/thehale/SimpleTimeTracker-WearOS/issues/8) is now solid, which means long term maintenance will be dramatically simplified.

Here's the current diff against your `dev` branch (updated regularly): https://github.com/thehale/SimpleTimeTracker-WearOS/compare/dev...wearos

Feel free to share your thoughts/suggestions!

**Comment by thehale** [comment]
@kantahrek and I have completed an MVP of a WearOS app! The [current PR](https://github.com/Razeeman/Android-SimpleTimeTracker/pull/162) is linked to this ticket.

Feel free to clone the [forked repo](https://github.com/thehale/SimpleTimeTracker-WearOS) to try it yourself!

**Comment by lucasfais** [comment]
Amazing work! It will be great to have my favorite android app on the watch. 

I see there is a new release with the `wear` apk. Is it bundled with `base` or `play` apk? Do you I have to use ADB to install it? Thanks.

**Comment by Razeeman** [comment]
@lucasfais Hello! `wear` apk works with `play` apk. Wear application was published to google play, but unfortunately there were some problems with the publishing review process, it would require a little more work to be done, and republished again after that. If everything goes well it will be released this weekend. At the moment `wear` apk can be installed on the watch through the ADB.

**Comment by lucasfais** [comment]
@Razeeman I see, thank you for your reply. I was able to install it. Works great! You guys rock!
