### ISSUE TITLE
Show currently active Activities in the Calendar tab

### ISSUE THREAD

**Issue by pragma-** [Razeeman/Android-SimpleTimeTracker#71]
Thanks for this incredible app.

One minor detail that's been bugging me. I have the Records tab configured to display as a calendar. When I have an Activity active for a while sometimes I like to look at the Records tab to see a timeline of my daily activities so far. Annoyingly, my currently active Activities are not displayed in the calendar timeline.

It would be so awesome if currently active Activities could be added to the Records tab with the end date temporarily updated to `now` on every tick. Then they would appear in the right place in the calendar timeline view!

**Comment by pragma-** [comment]
Seriously, this app is amazing. I tell everyone I know about it. 5 stars.

**Comment by Razeeman** [comment]
Hello! Thank you for the suggestion. Added this functionality in the latest commits. It will be in the next release if nothing significant comes up.

Next logical step would be to also add active activities to statistics tab. But this would be a much larger change, because detailed statistics will also change. Also with statistics there would be a problem with statistics widget, it can be updated automatically only once in half an hour, and statistics would show actual information updated every second but statistics widget would show different times. I think this will raise a lot of questions from users. Need to figure this out somehow.
