### ISSUE TITLE
Automatic spreadsheet export

### ISSUE THREAD

**Issue by alkero** [Razeeman/Android-SimpleTimeTracker#81]
Hi,

I have activated the automatic spreadsheet export, but it looks like the last one was done three days ago (possibly it has been triggered only once actually).

Is there certain conditions that could prohibit the automatic export to be performed?
Like the phone should be plugged or something? Thanks.

**Comment by Razeeman** [comment]
I've encountered the same issue, automatic backup stopped working after several days, but can't figure out yet why this is happening. There are no special conditions for it to work. Maybe it has something to do with phone reboot. Do you recall by any chance if you rebooted your phone lately?

**Comment by mertbakir** [comment]
It doesn't work for me too, today I come across a toast message: (not exact message) "error on automatic backup.  Please select a different location."

**Comment by mertbakir** [comment]
It doesn't work for me too, today I come across a toast message: (not exact message) "error on automatic backup.  Please select a different location."

**Comment by Razeeman** [comment]
I adjusted system settings so that the app wouldn't be killed by the system and removed from the memory (was trying to deal with another problem, activity notifications kept disappearing). Apparently this might also helped with auto backup because now it works consistently for a couple of weeks. On my xiomi phone mainly what helped is pinning the app in recents. Some additional information on this https://dontkillmyapp.com/xiaomi.

**Comment by alkero** [comment]
No problem any-more with this functionality. Thanks for the great app Razeeman. :)
