### ISSUE TITLE
some suggestions about editing records

### ISSUE THREAD

**Issue by mertbakir** [Razeeman/Android-SimpleTimeTracker#83]
Hello, I have some suggestions about the record editing view.

- Now button should be on the right side after +30 instead of before -30. So, it': easier to reach with right hand, since most people are right handed.
- Now button is kind of small, would be better if all buttons are equal size. (-30 -5 etc...)
- After selecting an activity, tag dropdown can be automatically triggered, in order to reduce 1 more click.
- Whole buttons, dropdowns etc can be moved to the bottom of the screen instead of top in order to improve reachability with one hand. Phone screens are too large and reaching top requires two handed usage. 
- The opening time shortcuts (-5 -30 +30...)  should be the ones for the end time instead of start time. When adding a new record or editing an existing one, usually we edit the end time keeping the start time as it's. I realised I'm constantly changing the focus from start time to end time manually. Generally speaking, number of times we need to edit the start time is lesser than the end time. This should reduce 1 more click.

**Comment by 123quhiwiwk** [comment]
I also have suggestions for the editing of the entry. I wanted to create a new issue until I saw that this issue already exists.

- The editing of entries does not display the +/- section by default. When I attempt to edit an entry, I must manually enable the +/- section to adjust the start and end times of an interval every time. I propose that there is an option to always display the +/- section collapsed by default.

- The current version of the time tracking app displays the start and end times of an interval/entry side by side, with small buttons and very small space between them. This makes it difficult for me to read and edit the times. Additionally, I find it more intuitive if the start and end times were displayed among each other. 

I made a sketch of my idea.
![suggestion_editing_entry](https://user-images.githubusercontent.com/70281681/222347589-cc72b0bf-b782-42b6-9c06-e049eb118d6e.png)

So my first suggestion is to provide an option to display the start and end times among each other, with bigger buttons and more space between them, to improve readability and ease of editing. My second suggestion is to add an option to always display the +/- section (both in the edit of current and finished entries).

Maybe we can combine our ideas, or my idea would also solve your problem.

**Comment by mertbakir** [comment]
@123quhiwiwk I'll say +1 to this. Edit screen has so much empty space that can be utilized.

**Comment by Razeeman** [comment]
Hello! Thank you for the great suggestions. 

@mertbakir 
`Now button should be on the right side` - agree. 
`Now button is kind of small, would be better if all buttons are equal size.` - unfortunately they can't have the same size, because width of the Now button depends on the text translations, so it is wrapped to its text and other buttons are spaced equally.
`After selecting an activity, tag dropdown can be automatically triggered` - 1 click would be reduced but only for people who use tags, for people who want to select comment or actions after selecting activity this would instead increase number of clicks by 1.
`Whole buttons, dropdowns etc can be moved to the bottom of the screen` - this is interesting but need to figure out how dropdown contents would be shown in this case. 
`The opening time shortcuts (-5 -30 +30...) should be the ones for the end time` - unfortunately we don't have analytics on this, so we can't tell for sure which shortcuts are used more. For example I'm mostly changing start time. Another thing is that edit record and edit current timer are basically the same screen, and edit current timer doesn't have end time, and I think that if these screens would have different default opened shortcuts - it may be confusing. 

@123quhiwiwk 
Screen does have a lot of empty space but only when dropdowns are closed. Main reason for time fields to be side by side is to have more space for dropdown content. In your suggested implementation time fields and dropdownds by itself could take up half a screen on smaller devices, so for example choosing activity would be inconvenient. Maybe different states can be implemented for this. For example if dropdowns are closed - show time fields under each other with +/- controls opened, if activity / comment / tag dropdown is selected - hide time fields completely, if actions dropdown is selected - leave current implementation with time fields side by side.

**Comment by mertbakir** [comment]
I think you can add some padding around the Now button, even though the text changes based on translation. Wouldn't it be good enough?

**Comment by Razeeman** [comment]
This may be possible, I'll try that.

**Comment by Razeeman** [comment]
Overall this screen has a lot of room for improvements but we need to be careful and consider all users use cases.

**Comment by mertbakir** [comment]
@Razeeman 

> `After selecting an activity, tag dropdown can be automatically triggered` - 1 click would be reduced but only for people who use tags, for people who want to select comment or actions after selecting activity this would instead increase number of clicks by 1.

How about triggering tags if there is a tag for the selected category?

**Comment by Razeeman** [comment]
Great idea. Implemented in the latest commits. Also moved Now button to the right and add padding to it to make it a little bigger.
