### ISSUE TITLE
[Feature] Allow negative time entries

### ISSUE THREAD

**Issue by clackwell** [Razeeman/Android-SimpleTimeTracker#86]
I track my working hours.

I want the statistics page to show how much time I have worked this week, including overtime and "undertime".

To handle overtime, I add a special entry that starts 00:00 on Monday, and spans the overtime period (3h or so) from previous the week. This way, the statistics page shows time worked this week so far, plus the overtime, and I can see at a glance how far away I am from my 40 hours per week.

Adding undertime in this fashion is not possible though, a time entry that start at 03:00 and ends 00:00 (on the same day) will be turned into a time entry with period 00:00. And this makes perfect sense to avoid adding faulty entries for the majority of the users.

I would like to add such negative entries anyway though, or to be able to configure a category to be subtracted from the total amount, to have things "add up" for me on the statistics page.

My current solution is to have "overtime" and "undertime" categories, have them enabled in the statistics page filter, and do the math on the fly:

![image](https://user-images.githubusercontent.com/6651253/223055314-589f9ea5-3f24-4f48-84f0-cb44497cf868.png)

Last but not least at all, thank you Razeeman & all contributors for this app and its UX that made perfect sense for me right out of the box (I know this cannot be taken for granted, I have looked at competing apps).

**Comment by Razeeman** [comment]
Hello! Thank you for the feedback and for the suggestion.

This would be a little hard to do because currently a lot of logic is based on the assumption that negative records are not allowed. For example there are a lot of checks on the edit record screen. Also I'm not sure how negative records can presented in calendar view. 

Wouldn't it be easier to set a different weekly goals according to previous week worktime? For example if there was a 3 hour overtime previous week, this week goal can be set to 37 hours. Alternatively if there was 3 hour under time, this week goal can be set to 43 hours. Weekly goals are shown on the statistics tab with the Week range selected, and there will be shown a goal time and a currently tracked time.

**Comment by clackwell** [comment]
Hi Anton, that sounds good. I had missed that feature so far, thank you.

Just to document it for someone who may come across this:

When adding/editing an activity:

![image](https://user-images.githubusercontent.com/6651253/223373562-ff75f179-21ec-4e1e-a731-39e31a6c5340.png)

At start of week, edit the activity, select "Goal time" and enter the desired week time:

![image](https://user-images.githubusercontent.com/6651253/223373901-d820a41a-da8d-4973-8720-1a866de528c2.png)

The statistics page then shows:

![image](https://user-images.githubusercontent.com/6651253/223374217-114b5a0a-5fd1-4ac1-b9d2-7730140d6078.png)

**Comment by alphanerdgen** [comment]
@Razeeman I'm glad I found this before asking for a countdown-style timer for those activities on which one would want to spend only a limited amount of time and not more like gaming, social media, etc. I'll use the alternative method shown above instead. Thanks for the app. It's awesome.
